### ISSUE TITLE
Line break on too many constructor arguments

### ISSUE THREAD

**Issue by MollocH** [cawolf/phpstorm-quick-mock#21]
First: thanks for adding the feature "Adding missing constructor properties".

I have a little adjustment:
since we have a PHPMD rule that limits the lines to 140 characters, I'd like the plugin to handle this.
First approach: count the characters and add line breaks if it exceeds 140 characters.
Second approach: if the constructor has >= 4 Parameters, do line breaks.
Third Approach: do line breaks by default.

Example:
``` 
$this->subject = new Authenticator(
    $this->clientRegistry->reveal(),
    $this->router->reveal(),
    $this->proxyHandler->reveal(),
    $this->logger->reveal()
);

**Comment by cawolf** [comment]
This should actually not be handled by any plugin, but by the formatter. According to the [plugin development documentation](https://www.jetbrains.org/intellij/sdk/docs/basics/architectural_overview/modifying_psi.html#whitespaces-and-imports), the formatter should actually handle all whitespace and formatting issues.

This can easily be adjusted under *Editor -> Code Style -> PHP*.
