### ISSUE TITLE
Quick mock for Methods

### ISSUE THREAD

**Issue by maxkaemmerer** [cawolf/phpstorm-quick-mock#24]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love it if this would also work for any Methods and not just Constructors.
As an example where this might be helpful:
ArgumentResolvers in Symfony get passed both a Request and ArgumentMetadata Object which would be great targets for a Prophecy.

**Describe alternatives you've considered**
I considered opening a PR for this but I have no idea how these Plugins are written and have only limited experience with Kotlin / Java. I'd be open to collaborate on it though.

**Comment by cawolf** [comment]
Hey @maxkaemmerer ,
thank you for your contribution.

When I first read the issue title, I found the idea quite interesting. As there are many different possible ways to handle this, can you please provide a detailed example, showing both before and after situations of the new functionality?

After reading the complete description, I'm not sure anymore if we thought of the same problem. You mention the `Request` and `ArgumentMetaData` as given parameters, which both are essentially data transfer objects / value objects (well, `Request` is a little bit more than that, but you get the idea). As @everzet mentioned in phpspec/prophecy#86 , you should actually avoid mocking value objects, but instead instantiate them directly (either by `__construct` or factory methods like `Request::create`).

I thought about other use cases of mocking methods besides constructors, but didn't yet come up with any, as usually, you should avoid passing complex units like services into methods directly, but mostly pure data (primitives, DTOs, VOs). Having said that, I'm still open for proposals, so if you have more input, I would definitely consider implementing this functionality.

**Comment by maxkaemmerer** [comment]
Well I'd imagine using it would work the same as within constructors.  
Opening the Context Menu with Alt + Enter within a method would give you the same Quick Mock Option as with Constructors. I don't know how it would work technically but I'd assume it's similar to constructors, probably some kind of reflection on the parameters. 

As for Use Cases, yes you are correct Value Objects should probably not be Mocked that was a bad example. Another Example from the Symfony world would be a service that gets services injected via setter Injection and a compiler pass, for example when using the strategy pattern or similar things. (while constructor injection is usually preferable to setter injection of course, sometimes this measure is needed)
Another example might be an invokable controller that gets the needed services injected in the controller methods and not the constructor.

Thinking about it more, it might encourage bad practices like setter injection.
I find myself missing this feature sometimes though, maybe that says more about the code I'm working on though.

**Comment by cawolf** [comment]
Im kinda torn right now. Yes, for special cases like Strategies and CompilerPasses this would be handy. However, your argument of encouraging bad practice really holds me back. 

For now, I would rather delay this feature and close this proposal for the time being. Maybe someone else comes up with a killer use case and an idea how to prevent bad designs. Is that ok for you?

**Comment by maxkaemmerer** [comment]
Yeah sure.
As I said before, it would probably do more harm than good.
Thanks for considering it though.
