### ISSUE TITLE
Overwriting of PHPUnit TestCase properties 

### ISSUE THREAD

**Issue by cHeeSaW** [cawolf/phpstorm-quick-mock#26]
**Describe the bug**
When the tested class has parameters in the constructor which are named like properties of the PHPUnit `TestCase` class, these would be overwritten after using quickmock

**To Reproduce**
1. Create a class with a contructor parameter called `data`
2. Create a test for this class
3. Use quickmock

**Expected behavior**
Maybe detection if `TestCase` already reservers a name and rename the generated property

**Comment by cawolf** [comment]
Whenever mock names collide with existing inherited properties, a suffix will now be added to the name to distinguish them.
